# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UEE Handle'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Игровая Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар пользователя'),
        ),
    ]
