# Generated by Django 2.1.3 on 2018-11-22 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата Создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата Редактирования')),
                ('published', models.BooleanField(default=True, help_text='Без галочки запись будет считаться черновиком.', verbose_name='Опубликовано')),
                ('moderation', models.BooleanField(default=True, help_text='По умолчанию все новые публикации одобреные, что бы это изменить уберите галочку, после чего запись будет считатся отклоненной.', verbose_name='Одобрено')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Слаг — это вариант названия, подходящий для URL. Обычно содержит только латинские буквы в нижнем регистре, цифры и дефисы.', max_length=60, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, help_text='По Умолчанию первый абзац Контента, при необходимости можно изменить.', verbose_name='Описание')),
                ('main', models.BooleanField(default=False, help_text='Решает будет ли запись видна на главной странице.', verbose_name='Главная страница')),
                ('ordering', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Сортировка')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Миниатюра')),
                ('video_link', models.TextField(blank=True, default='', verbose_name='Video from YpuTube or Vimeo')),
                ('big_thumbnail', models.BooleanField(default=False, help_text='Если отмечено, на превью будет большая миниатюра.', verbose_name='Большая миниатюра')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
