# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(max_length=200),
        ),
    ]
