# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171016_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='moderation',
            field=models.BooleanField(default=False, help_text='Если отмечено, запись заблокирована модератором.', verbose_name='Модерация'),
        ),
    ]
