# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171209_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ordering',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Описание - будет выводится в мета теге description.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название определяет, как катерогия будет отображаться на сайте.', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Категории, в отличие от меток, могут иметь иерархию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category', verbose_name='Родительская'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Слаг — это вариант названия, подходящий для URL. Обычно содержит только латинские буквы в нижнем регистре, цифры и дефисы.', verbose_name='Слаг'),
        ),
    ]
