# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171214_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main',
            field=models.BooleanField(default=False, help_text='Решает будет ли запись видна на главной странице.', verbose_name='Главная страница'),
        ),
    ]
