# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modification date')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.Category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBaseAbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Modification date')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('published', models.BooleanField(default=True, help_text='Если стоит галочка запись будет доступна на сайте.', verbose_name='Опубликовано')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('knowledgebaseabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.KnowledgeBaseAbstractModel')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('race', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('current_ceo', models.CharField(blank=True, max_length=255)),
                ('founder', models.CharField(blank=True, max_length=255)),
                ('founded', models.CharField(blank=True, max_length=255)),
                ('demographic', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Category', verbose_name='Катерогия')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('database.knowledgebaseabstractmodel',),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('knowledgebaseabstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='database.KnowledgeBaseAbstractModel')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('focus', models.CharField(blank=True, max_length=255)),
                ('prod_state', models.CharField(blank=True, max_length=255)),
                ('max_crew', models.CharField(blank=True, max_length=255)),
                ('cargo_capacity', models.CharField(blank=True, max_length=255)),
                ('rec_cost', models.CharField(blank=True, max_length=255)),
                ('pledge_cost', models.CharField(blank=True, max_length=255)),
                ('null_cargo_mass', models.CharField(blank=True, max_length=255)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('beam', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Category', verbose_name='Катерогия')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Company')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('database.knowledgebaseabstractmodel',),
        ),
    ]
