# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('industry', models.CharField(blank=True, max_length=80, null=True)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('current_ceo', models.CharField(blank=True, max_length=50, null=True)),
                ('founder', models.CharField(blank=True, max_length=50, null=True)),
                ('founded', models.CharField(blank=True, max_length=50, null=True)),
                ('demographic', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True)),
                ('focus', models.CharField(blank=True, max_length=60, null=True)),
                ('prod_state', models.CharField(blank=True, max_length=60, null=True)),
                ('max_crew', models.SmallIntegerField(blank=True, null=True)),
                ('cargo_capacity', models.IntegerField(blank=True, null=True)),
                ('rec_cost', models.IntegerField(blank=True, null=True)),
                ('pledge_cost', models.IntegerField(blank=True, null=True)),
                ('null_cargo_mass', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('beam', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
