# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('focus', models.CharField(blank=True, max_length=60, null=True)),
                ('prod_state', models.CharField(blank=True, max_length=60, null=True)),
                ('max_crew', models.SmallIntegerField(blank=True, null=True)),
                ('cargo_capacity', models.IntegerField(blank=True, null=True)),
                ('rec_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True)),
                ('pledge_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('null_cargo_mass', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('beam', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Company')),
            ],
        ),
    ]
