# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_company_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='pledge_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='rec_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
