# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_historicalcompany_historicalship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalship',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='focus',
        ),
    ]
