# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171105_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('published', models.BooleanField(default=True, help_text='Решает будет ли запись видна на сайте.', verbose_name='Опубликовано')),
                ('moderation', models.BooleanField(default=False, help_text='Если отмечено, запись заблокирована модератором.', verbose_name='Модерация')),
                ('slug', models.CharField(default='', max_length=250, unique=True, verbose_name='Slug')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='', max_length=250, verbose_name='Scrapy Url')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Keywords')),
                ('image', models.ImageField(blank=True, default='', upload_to='category_images/', verbose_name='Image')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('published', models.BooleanField(default=True, help_text='Решает будет ли запись видна на сайте.', verbose_name='Опубликовано')),
                ('moderation', models.BooleanField(default=False, help_text='Если отмечено, запись заблокирована модератором.', verbose_name='Модерация')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_property', to='database.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category property',
                'verbose_name_plural': 'Category properties',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('published', models.BooleanField(default=True, help_text='Решает будет ли запись видна на сайте.', verbose_name='Опубликовано')),
                ('moderation', models.BooleanField(default=False, help_text='Если отмечено, запись заблокирована модератором.', verbose_name='Модерация')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Slug')),
                ('url', models.CharField(blank=True, default='', max_length=250, verbose_name='Url')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('sky', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Sky')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Keywords')),
                ('image', models.ImageField(blank=True, default='', upload_to='Itemimeges/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Price')),
                ('promo', models.BooleanField(default=False, help_text='Show this Item on Home page?', verbose_name='Published')),
                ('description', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='database.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('published', models.BooleanField(default=True, help_text='Решает будет ли запись видна на сайте.', verbose_name='Опубликовано')),
                ('moderation', models.BooleanField(default=False, help_text='Если отмечено, запись заблокирована модератором.', verbose_name='Модерация')),
                ('value', models.CharField(default='', max_length=250, verbose_name='Value')),
                ('category_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_property', to='database.CategoryProperty', verbose_name='Propery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_product', to='database.Item', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Item property',
                'verbose_name_plural': 'Item properties',
            },
        ),
    ]
