# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20171003_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='null_cargo_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
