# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20171003_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='null_cargo_mass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
