# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_category_categoryproperty_item_itemproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='product',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_Item', to='database.Item', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
