# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20171105_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='categoryproperty',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='itemproperty',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modification date'),
        ),
    ]
