# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20171005_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
