# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20171005_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ship',
            options={'ordering': ['name']},
        ),
    ]
