# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-upload_date']},
        ),
    ]
